color0 #050b10
color1 #857960
color2 #82967f
color3 #96937b
color4 #97a6bb
color5 #6c7b91
color6 #83a2a3
color7 #eff3ef
color8 #62676c
color9 #bfae87
color10 #a4b89b
color11 #bbb999
color12 #bbcce7
color13 #8e9fbb
color14 #a5c9ca
color15 #f3f7f3

cursor                #e9efeb
cursor_text_color     #070e15
background            #070e15
foreground            #e9efeb
selection_foreground  #e9efeb
selection_background  #20262c
active_border_color   #97a6bb
inactive_border_color #20262c
url_color             #97a6bb

active_tab_foreground   #070e15
active_tab_background   #97a6bb
inactive_tab_foreground #9aa7a1
inactive_tab_background #20262c
cursor_trail_color      #9aa7a1
