[[entry]]
played_at = "2026-10-08T07:07:37Z"
path = "https://radio.cliamp.stream/lofi/stream"
title = "Lofi"

[[entry]]
played_at = "2026-10-05T18:19:10Z"
path = "https://radio.cliamp.stream/meditative/stream"
title = "Meditative"

[[entry]]
played_at = "2026-09-25T10:09:47Z"
path = "https://radio.cliamp.stream/synthwave/stream"
title = "Synthwave"
